### ISSUE TITLE
ImportError No Module named daemon.daemon

### ISSUE THREAD

**Issue by dimaspencer84** [errbufferoverfl/usb-canary#6]
I tried running the tool on Kali Linux, but I get this error message. I installed all the dependencies and configured the settings.json file and put it in the root directory as specified but I still get this error.
Did I miss something ?

    # ./usb-canary.py start
    Traceback (most recent call last):
    File "./usb_canary.py", line 34, in <module>
    from canary.daemon.daemon import Daemon
    ImportError: No module named daemon.daemon

**Comment by cclauss** [comment]
https://github.com/probablynotablog/usb-canary/blob/master/usb_canary.py#L35

**Comment by errbufferoverfl** [comment]
Thanks @cclauss - @dimaspencer84 if you have any further issues let me know, otherwise I will close off this issue for now.

**Comment by cclauss** [comment]
My sense is that this problem in *not resolved*.  [usb_canary.py line 35](https://github.com/probablynotablog/usb-canary/blob/master/usb_canary.py#L35) still points to a file that no longer exists in the project.

@dimaspencer84 can you please confirm?  If you still have this problem, can you please put a `#` in front of this line of code on your computer to comment it out and then tell us if this resolves the problem?

**Comment by errbufferoverfl** [comment]
Ah you seem to be right my apologies.

**Comment by errbufferoverfl** [comment]
@dimaspencer84 will need to put a # in front of the old import and include `from daemon import Daemon`.

I have fixed this issue in the repository, you can find a patched version under releases.

**Comment by dimaspencer84** [comment]
Hi!
Sorry for the late reply. Now I get this error message with the new release:
    
```
    # ./usb-canary.py start
    Traceback (most recent call last)
    File "./usb_canary.py", line 28, in <module>
    from daemon import Daemon
    ImportError: cannot import name Daemon
```
Is it on my side this time ?

**Comment by errbufferoverfl** [comment]
Hey @dimaspencer84 no stress about the delay! I quickly downloaded the latest release and had it up and running with no issues. Maybe just double check that `sander-daemon` has successfully been installed and give it another go.

If you still have this issue please don't hesitate to let me know I'll keep looking into the possible cause this morning.

**EDIT:** I used a fresh copy of Debain Jessie and ran `sudo pip install -r requirements.txt` and it ran with no issue. ~Can I confirm if you are using Ubuntu or Debian - it shouldn't really matter but I just want to make sure there is something I overlooked when testing the original pull request.~

I used a fresh copy of Ubuntu 16.04.2 LTS and found the same results - no traceback call or issues with the import. I'm sorry you're having these difficulties!

**Comment by dimaspencer84** [comment]
It worked with Ubuntu finally. Thank you and Good Luck !
