### ISSUE TITLE
Pushover support

### ISSUE THREAD

**Issue by helpsterTee** [errbufferoverfl/usb-canary#9]
- [x] Feature Request
- [ ] Bug Report 

## Expected Behavior

It would be nice to use Pushover as an alternative channel of notification transportation.

## Current Behavior

usb-canary does not currently use Pushover as a channel of notification transportation.

## Possible Solution

Implement Pushover as a channel of notification transportation

## Steps to Reproduce (for bugs)

N/A

## Context

I like to use Pushover for notification transportation. Unfortunately this is currently not supported.

**Comment by errbufferoverfl** [comment]
Thanks for your support! Your PR has been merged and a new release created.
